image: maven:3.8.6-openjdk-8-slim

default:
  tags:
    - cpu
    - common

stages:
  - validate
  - build
  - test

Checkstyle job:
  stage: validate
  script:
    - mvn checkstyle:checkstyle
  artifacts:
    paths:
      - target/checkstyle-result.xml
    reports:
      codequality: target/checkstyle-result.xml

Build job:
  stage: build
  script:
    - mvn compile

Test code:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - target/site/jacoco
    reports:
      junit: target/surefire-reports/*.xml
